version: '3.8'
services:
  datadog:
    build: .
    env_file:
      - ../.env
    ports:
      - "8126:8126"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro


